version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_practice_network
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - database_practice_network
    command:
      - --auth

volumes:
  postgres_data:
  mongodb_data:

networks:
  database_practice_network:
